blank_issues_enabled: false
contact_links:
  - name: 📩 Contactar a MaxRetana
    url: mailto:maxretana.dev@gmail.com
    about: Si tienes dudas generales, puedes escribirme directamente.

  - name: 📩 Contactar a Ewar22
    url: mailto:eduardmontano.dev@gmail.com
    about: Si tienes dudas generales, puedes escribirme directamente.